### ISSUE TITLE
OS-specific gitignores? (I want .DS_Store ignored on macOS)

### ISSUE THREAD

**Issue by theonlygusti** [zachlatta/gitignorer#6]
I cursorily checked `gitignorer list` and couldn't find `macOS` or `DS_Store` or `OSX` etc. gitignore boilerplate.

I would like to ignore at least `.DS_Store` as I always had done in the past, but a quick google search "macOS gitignore" threw me https://github.com/github/gitignore/blob/master/Global/macOS.gitignore, which seems to be more comprehensive.

In my case, I would love to have a feature in gitignorer to ignore these kinds of files: `gitignorer create python macos` or `gitignorer create python DS_Store` for example. Now that I have such a great tool to generate my gitignores for me, manually editing it _every time_  to add these OS-files feels... unpleasant.

And, by extension, I wonder if there are similar artefacts/files that would be useful to have gitignore boilerplate for in other OSes.

Idk how best to solve this issue, but I just don't want to have to manually edit every `.gitignore` that is created by `gitignorer` to add a few (identical) lines every time.

**Comment by zachlatta** [comment]
Hey @theonlygusti, I think a better approach to solving this problem will be to use a global `.gitignore` file (https://help.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer).

For example, my global `.gitignore` file at https://github.com/zachlatta/dotfiles/blob/master/gitignore has macOS's `.DS_Store` in it.

If you'd be up to submit a PR to add global `.gitignore` support to gitignorer, I think that'd be a great addition.
